[package]
name = "comic-name"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.9", package = "gtk4", features = ["gnome_47"] }
serde = { version = "1.0", features = ["derive"] }
ureq = { version = "2.12", features = ["json"] }

[dependencies.adw]
package = "libadwaita"
version = "0.7"
features = ["v1_6"]

[dev-dependencies]
serde_json = "1.0"
